258
a:5:{s:8:"template";a:5:{s:9:"index.tpl";b:1;s:10:"header.tpl";b:1;s:10:"errors.tpl";b:1;s:8:"post.tpl";b:1;s:10:"footer.tpl";b:1;}s:6:"config";a:1:{s:12:"english.conf";b:1;}s:9:"timestamp";i:1381890023;s:7:"expires";i:1381933223;s:13:"cache_serials";a:0:{}}<!DOCTYPE html>
<html>
<head>
   <title>Home - Ingvar den vittfarne på nya äventyr</title>

   <link rel="stylesheet" href="http://ilostatic.one.com/iloapp/blog/css/mobile-build.css" type="text/css" media="screen"/>

   <!--<link rel="apple-touch-icon" href="http://ilostatic.one.com/iloapp/blog/"/>-->

   <meta name="robots" content="noindex,noarchive"/>
   <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;"/>
      </head>
<body><div class="container"><div class="header"><a href="?Home">&#xab; Home</a><h1><a href="?Home">Ingvar den vittfarne på nya äventyr</a></h1></div><div class="content"><div class="post"><h2><a href="?Home&amp;post=24">Weiqi och folkvandring</a><a class="category" href="?Home&amp;category=0">Singapore</a></h2><p class="time">Posted by <a href="?Home&amp;user=8">Anders</a> 17 Dec, 2009 14:25:44</p><div class="postContent">Jag har ju kommit igång att spela Go igen, eller Weiqi som det egentligen heter i någon mening. Det har börjat med att jag går en nybörjarkurs arrangerad av Singapore Weiqi Association. Vid senaste kurstillfället spelade jag ett parti med en äldre herre som tidigare jobbat vid CERN och var med och skapade internet. <br/><br/>Peter Hägglund kommer hit över nyår, Larsendahls sista helgen i mars och Kruse planerar. Således verkar folkvandringen ha börjat. När kommer Du?<br/><br/>
</div><ul class="controls"><li><a href="?NewComment&amp;post=24#comments"class="control">Comments(2)</a></li></ul></div><!-- End of post --><div class="post"><h2><a href="?Home&amp;post=23">Julfin i håret</a><a class="category" href="?Home&amp;category=0">Singapore</a></h2><p class="time">Posted by <a href="?Home&amp;user=8">Anders</a> 10 Dec, 2009 13:44:40</p><div class="postContent">Idag var jag hos frisören. Fast jag var lite tveksam då salongen heter Two Way Holistic. Jag lurade mig själv dit eftersom vi som är medlemmar i NUS Staff Club har ordentlig rabatt: 14 SGD istället för ordinarie 22 SGD. Men jag blev klippt, hårtvättad med huvudmassage samt klippt lite mer, och mår hårfint.<br/><br/>Imorgon (fredag) ska jag på julbord med lucia på Equinox å 69:e våningen i Swissôtel The Stamford.<br/><br/>
</div><ul class="controls"><li><a href="?NewComment&amp;post=23#comments"class="control">Comments(1)</a></li></ul></div><!-- End of post --><div class="post"><h2><a href="?Home&amp;post=22">3 Rochester Park</a><a class="category" href="?Home&amp;category=0">Singapore</a></h2><p class="time">Posted by <a href="?Home&amp;user=8">Anders</a> 04 Dec, 2009 15:43:23</p><div class="postContent">Nu har jag frekventerat 3 Rochester Park, det vill säga näringsstället Da Paolo Bistro Bar. Italiensktinspirerat. Här var det lite lugnare än på de två tidigare ställena, då de andra hade en livfulla barer. Jag började med dagens soppa - tomatsoppa med räkor (två stycken). Smakrik! Jag fortsatte med klassikern Spaghetti alla Carbonara. Grädde och bacon - vilken västerländsk kontrast till all curry och oljiga grönsaker! En ren njutning. Jag sköljde ner måltiden med två glas av husets vita italienska vin. Lättdrucket och harmlöst. Som dessert tog jag lite färska frukter. Problemet med denna rätt är att på finare ställen här så får man en liten portion innehållande exotiska frukter såsom (tämligen smaklösa) jordgubbar och blåbär! Slutbetyget är trots detta bästa stället å Rochester Park hittills. <br/><br/>
</div><ul class="controls"><li><a href="?NewComment&amp;post=22#comments"class="control">Comments(2)</a></li></ul></div><!-- End of post --><div class="post"><h2><a href="?Home&amp;post=21">Kubtävling!</a><a class="category" href="?Home&amp;category=0">Singapore</a></h2><p class="time">Posted by <a href="?Home&amp;user=8">Anders</a> 30 Nov, 2009 13:47:49</p><div class="postContent">Jag har nu deltagit i en kubtävling i ett sjuttonde land - Malaysia. Tävlingen var i Kuala Lumpur och dit åker man lämpligen buss från Singapore, vilket tar runt fem timmar. Förutsatt att alla passagerare kommer igenom tullen ordentligt. Man kan även åka tåg - det ska jag göra någon annan gång.<br/><br/><a href="http://www.worldcubeassociation.org/results/c.php?allResults=All+Results&amp;competitionId=MalaysianOpen2009" target="_blank">Malaysian Cube Open 2009</a> var den första kubtävlingen i Malaysia och den lockade 145 deltagare. Mycket folk och ny arrangör - givetvis sprack tisdschemat ordentligt första dagen, men andra dagen gick det som smort. <br/><br/>Bästa resultat på tävlingen var Piti:s i 3x första omgången med följande snitt och enskilda tider 10.42 (9.27 10.97 11.77 7.88 11.02). Detta rankar honom tvåa i världen på både snitt- och singeltid. Ett annat toppresultat var Gooi Ying Chyi i Square-1 som snittade 16.85, vilket renderar en femteplats å världsrankningen.<br/><br/>För egen del så är jag i stort nöjd med mina resultat. Magic gick uselt då min Magic håller på att haverera och 2x gick några sekunder för långsamt. Jag satte personligt snittrekord på pyraminx med 16.92 (för övrigt samma snittid som på tvåan....), mest tack vare en ny Pyraminx som inte poppar. Square-1 var mest händleserik. Jag började med sub-2-min, vilket är bra för mig och gjorde att jag klarade tidsgränsen för fem försök. Tredje var en riktig turblandning där allt föll på plats och tiden slutade på 45 s, men blev DNF eftersom jag hade mittlagret fel. Så går det när man inte kollar tillräckligt. På ett sätt är jag glad över DNF:en, för annars skulle jag ha ett rekord som jag aldrig skulle slå i framtiden. Sista försöket blev också DNF då jag tappade fokus, gjorde fel i paritetsdragserien och kom bort helt och hållet. 3x flöt på bra, stabila lösningar och ett snitt på 41.33. Stabila tider även på 3x enhands runt 1:3x.xx, vilket dock inte räckte for fem försök. 4x gjorde jag en bra tid på 3:20.28, där jag antagligen skulle satt singelrekord om jag inte poppat en mittbit. <br/><br/>Mycket kul tävling och många nya kubvänner. Nu väntar <a href="http://www.worldcubeassociation.org/results/c.php?i=BangkokOpen2010" target="_blank">Bangkok Open 2010</a> och <a href="http://www.worldcubeassociation.org/results/c.php?i=JakartaOpen2010" target="_blank">Jakarta Open 2010</a> i januari nästa år!<br/><br/>
</div><ul class="controls"><li><a href="?NewComment&amp;post=21#comments"class="control">Comments(4)</a></li></ul></div><!-- End of post --><div class="post"><h2><a href="?Home&amp;post=20">När Anders slaskar ...</a><a class="category" href="?Home&amp;category=0">Singapore</a></h2><p class="time">Posted by <a href="?Home&amp;user=0">Göran</a> 30 Nov, 2009 08:30:21</p><div class="postContent"><p>...då julen braskar.</p>
<p>Undrar om det finns något motsvarande uttryck i Singapore? <br/></p>
</div><ul class="controls"><li><a href="?NewComment&amp;post=20#comments"class="control">Comments(4)</a></li></ul></div><!-- End of post --><div class="post"><h2><a href="?Home&amp;post=19">Kubande under Hajj</a><a class="category" href="?Home&amp;category=0">Singapore</a></h2><p class="time">Posted by <a href="?Home&amp;user=8">Anders</a> 27 Nov, 2009 02:29:39</p><div class="postContent">Idag är vi lediga i Singapore - det är <a href="http://sv.wikipedia.org/wiki/Hajj" target="_blank">Hajj</a>!<br/><br/>Om några timmar åker jag till Kuala Lumpur för en <a href="http://www.worldcubeassociation.org/results/c.php?i=MalaysianOpen2009" target="_blank">Rubiks-kub-tävling</a>. Med över 200 anmälda så blir det den största tävlingen i Asien hittills och den tredje största i välden efter VM 2009 och VM 2007. Jag kommer att åka buss, vilket tar runt fem timmar. Ett utmärkt tillfälle att träna på att vrida på kuben!<br/><br/>
</div><ul class="controls"><li><a href="?NewComment&amp;post=19#comments"class="control">Comments(0)</a></li></ul></div><!-- End of post --><div class="post"><h2><a href="?Home&amp;post=18">Kaffe</a><a class="category" href="?Home&amp;category=0">Singapore</a></h2><p class="time">Posted by <a href="?Home&amp;user=8">Anders</a> 18 Nov, 2009 13:43:42</p><div class="postContent">Som på alla ställen med lokalt kaffe så bör man veta vad man beställer. Kaffet här är från Indonesien och bryggs/dras i strumpliknande tygfilter. Det lokala ordet för kaffe är "kopi", men beställer man kopi, eller kopi-c, så får man kaffe med kondenserad mjölk och socker. Vill man ha svart kaffe så får man beställa "kopi-o" men då får man trots det socker i kaffet. Vill man ha endast kaffe så får man beställa 'kopi-o-kosong', vilket jag gör dagligen och betalar S$0,60 för drycken. Kopi-o kostar S$0,70 och kopi S$0,80. Vill man ha kaffe med mjölk men inget socker så får man beställa kopi-c-kosong. Det finns fler varianter, men i huvudsak räcker det med dessa.<br/><br/>Midvinterbalen som nämndes i förra inlägget ordnades av svenska företagarföreningen i Singapore ska kanske tilläggas. Det var ett tillfälle att träffa andra svenskar och klä sig vackert. En av klänningarna på tillställningen gick på S$2800.<br/><br/>
</div><ul class="controls"><li><a href="?NewComment&amp;post=18#comments"class="control">Comments(1)</a></li></ul></div><!-- End of post --><div class="post"><h2><a href="?Home&amp;post=17">Midvinterbal</a><a class="category" href="?Home&amp;category=0">Singapore</a></h2><p class="time">Posted by <a href="?Home&amp;user=8">Anders</a> 14 Nov, 2009 10:59:51</p><div class="postContent">Tiden rör på sig och jag håller på att byta om inför Midvinterbalen som avhålls ikväll i balsalen å Raffles Hotel. Twitter, out.<br/><br/>
</div><ul class="controls"><li><a href="?NewComment&amp;post=17#comments"class="control">Comments(0)</a></li></ul></div><!-- End of post --></div><div class="paging"><a class="previous" href="?Home&amp;category=0&amp;page=1"></a><a class="next" href="?Home&amp;category=0&amp;page=3"></a></div><div class="footer"><a href="?About">Info</a><a href="?Categories">Categories</a><a href="?Login">Log In</a><a href="?Home&amp;desktop">Non-mobile site</a></div></div><!-- End of container --></body></html>