258
a:5:{s:8:"template";a:5:{s:9:"index.tpl";b:1;s:10:"header.tpl";b:1;s:10:"errors.tpl";b:1;s:8:"post.tpl";b:1;s:10:"footer.tpl";b:1;}s:6:"config";a:1:{s:12:"english.conf";b:1;}s:9:"timestamp";i:1381890190;s:7:"expires";i:1381933390;s:13:"cache_serials";a:0:{}}<!DOCTYPE html>
<html>
<head>
   <title>Home - Ingvar den vittfarne på nya äventyr</title>

   <link rel="stylesheet" href="http://ilostatic.one.com/iloapp/blog/css/mobile-build.css" type="text/css" media="screen"/>

   <!--<link rel="apple-touch-icon" href="http://ilostatic.one.com/iloapp/blog/"/>-->

   <meta name="robots" content="noindex,noarchive"/>
   <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;"/>
      </head>
<body><div class="container"><div class="header"><a href="?Home">&#xab; Home</a><h1><a href="?Home">Ingvar den vittfarne på nya äventyr</a></h1></div><div class="content"><div class="post"><h2><a href="?Home&amp;post=9">Papper som ska vändas</a><a class="category" href="?Home&amp;category=0">Singapore</a></h2><p class="time">Posted by <a href="?Home&amp;user=8">Anders</a> 08 Oct, 2009 14:42:55</p><div class="postContent">Jag har nu lyckats föra över pengar från Nordea till min bank härnere, DBS. Jag begärde överföringen i fredags och i tisdags hade jag pengarna här. Och detta helt och hållet via Nordeas internetbank. Tänk vad enkelt det är ibland. Fast alla saker går inte lika fort. Det tar runt två veckor att trycka upp visitkort och fixa mitt universitetsidkort. Vidare så ska jag bli ersatt för mina resekostnader; en procedur som också beräknas ta två veckor. Eftersom papper ska vändas några gånger så kan man kanske ha förståelse för detta, men enligt uppgift så ska det ta mer än tre veckor att få igenom ett autogiro mellan två konton i samma bank. Svårförståeligt. Idag gick jag med i <a href="http://www.nus.edu.sg/staffclub" target="_blank">Staff Club</a> vid universitetet, och deras medlemskort tar en månad att fixa fram...<br/><br/>Staff Club orndar med en promenad i Little India på lördag med avslutande middag. Att få sig en dos indisk kultur när <a href="http://sv.wikipedia.org/wiki/Diwali" target="_blank">Deepavali</a> står för dörren blir nog inte så dumt. Senare på lördagskvällen ska jag träffa Martin, en annan svensk i förskingringen, och några av hans kollegor för att ta en öl. Eventuellt blir det även ett kubmöte i helgen. Det vankas kubtävling sista helgen i november. <br/><br/>Nu har jag en T715 med telefonnummer +65 9815 4442.<br/><br/>
</div><ul class="controls"><li><a href="?NewComment&amp;post=9#comments"class="control">Comments(3)</a></li></ul></div><!-- End of post --></div><div class="paging"></div><div class="footer"><a href="?About">Info</a><a href="?Categories">Categories</a><a href="?Login">Log In</a><a href="?Home&amp;desktop">Non-mobile site</a></div></div><!-- End of container --></body></html>