258
a:5:{s:8:"template";a:5:{s:9:"index.tpl";b:1;s:10:"header.tpl";b:1;s:10:"errors.tpl";b:1;s:8:"post.tpl";b:1;s:10:"footer.tpl";b:1;}s:6:"config";a:1:{s:12:"english.conf";b:1;}s:9:"timestamp";i:1381890259;s:7:"expires";i:1381933459;s:13:"cache_serials";a:0:{}}<!DOCTYPE html>
<html>
<head>
   <title>Home - Ingvar den vittfarne på nya äventyr</title>

   <link rel="stylesheet" href="http://ilostatic.one.com/iloapp/blog/css/mobile-build.css" type="text/css" media="screen"/>

   <!--<link rel="apple-touch-icon" href="http://ilostatic.one.com/iloapp/blog/"/>-->

   <meta name="robots" content="noindex,noarchive"/>
   <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;"/>
      </head>
<body><div class="container"><div class="header"><a href="?Home">&#xab; Home</a><h1><a href="?Home">Ingvar den vittfarne på nya äventyr</a></h1></div><div class="content"><div class="post"><h2><a href="?Home&amp;post=6">Mat &amp; flyttkartonger</a><a class="category" href="?Home&amp;category=0">Singapore</a></h2><p class="time">Posted by <a href="?Home&amp;user=8">Anders</a> 02 Oct, 2009 16:24:46</p><div class="postContent">Efter några dagars suktande så har jag precis nu öppnat den flaska Highland Park (16y) som jag köpte i Frankfurt. Sláinte! Mina måltider intar jag nästan helt på universitetsområdet. Prisbilden där är betydligt bättre än på annat håll. Vad sägs om en lunch för 15-20 kr? Fast då får man trängas med studenter i trettiogradig värme. Det lär bli mer pratat om mat i denna blogg. Mat är gott. Mat är viktigt. Bäst uttryckt i den kinesiska hälsningsfrasen: Har du ätit?<br/><br/>Idag fick jag mina fem flyttkartonger som har flugit med Thai. Själv åkte jag med Singapore Airlines. Transporten var endast ordnad till Changi Airport, Singapores flygplats, och därifrån skulle jag själv ta bråten genom tullen och transportera den vidare. Dock finns det alltid tjänstvilliga personer som för en ersättning kan göra det som man inte själv vill. Wei Wei, som jobbar på personalavdeningen, var kontaktperson för sändningen och hon fixade en transportör som kunde ta godset genom tullen och transportera det till mitt kontor för det facila priset av 250 kr. Tullen ville ha drygt denna summa för att administrera det hela. Allt gick väldigt smidigt, trots att sändningen ett tag var på väg till Vancouver, och kartongerna var inte onödigt tilltufsade.<br/><br/>Hittills har allt gått som på räls; fast nu i helgen blir det stora elddopet. Jag ska på lägenhetsvisningar och bestämma mig för var jag ska bo.<br/><br/>Javisst ja, jag höll på att glömma att nämna att det var en stor jordbävning alldeles i närheten nyligen. Den kändes i Singapore och oroliga människor utrymde byggnader som skakade. Själv märkte jag inget. Får skylla på tidsomställningen. <br/><br/><br/><br/><br/>
</div><ul class="controls"><li><a href="?NewComment&amp;post=6#comments"class="control">Comments(1)</a></li></ul></div><!-- End of post --></div><div class="paging"></div><div class="footer"><a href="?About">Info</a><a href="?Categories">Categories</a><a href="?Login">Log In</a><a href="?Home&amp;desktop">Non-mobile site</a></div></div><!-- End of container --></body></html>