258
a:5:{s:8:"template";a:5:{s:9:"index.tpl";b:1;s:10:"header.tpl";b:1;s:10:"errors.tpl";b:1;s:8:"post.tpl";b:1;s:10:"footer.tpl";b:1;}s:6:"config";a:1:{s:12:"swedish.conf";b:1;}s:9:"timestamp";i:1375196126;s:7:"expires";i:1375239326;s:13:"cache_serials";a:0:{}}<!DOCTYPE html>
<html>
<head>
   <title>Startsida - Ingvar den vittfarne på nya äventyr</title>

   <link rel="stylesheet" href="http://ilostatic.one.com/iloapp/blog/css/mobile-build.css" type="text/css" media="screen"/>

   <!--<link rel="apple-touch-icon" href="http://ilostatic.one.com/iloapp/blog/"/>-->

   <meta name="robots" content="noindex,noarchive"/>
   <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;"/>
      </head>
<body><div class="container"><div class="header"><a href="?Home">&#xab; Startsida</a><h1><a href="?Home">Ingvar den vittfarne på nya äventyr</a></h1></div><div class="content"><div class="post"><h2><a href="?Home&amp;post=21">Kubtävling!</a><a class="category" href="?Home&amp;category=0">Singapore</a></h2><p class="time">Skapad av <a href="?Home&amp;user=8">Anders</a> 30 nov, 2009 13:47:49</p><div class="postContent">Jag har nu deltagit i en kubtävling i ett sjuttonde land - Malaysia. Tävlingen var i Kuala Lumpur och dit åker man lämpligen buss från Singapore, vilket tar runt fem timmar. Förutsatt att alla passagerare kommer igenom tullen ordentligt. Man kan även åka tåg - det ska jag göra någon annan gång.<br/><br/><a href="http://www.worldcubeassociation.org/results/c.php?allResults=All+Results&amp;competitionId=MalaysianOpen2009" target="_blank">Malaysian Cube Open 2009</a> var den första kubtävlingen i Malaysia och den lockade 145 deltagare. Mycket folk och ny arrangör - givetvis sprack tisdschemat ordentligt första dagen, men andra dagen gick det som smort. <br/><br/>Bästa resultat på tävlingen var Piti:s i 3x första omgången med följande snitt och enskilda tider 10.42 (9.27 10.97 11.77 7.88 11.02). Detta rankar honom tvåa i världen på både snitt- och singeltid. Ett annat toppresultat var Gooi Ying Chyi i Square-1 som snittade 16.85, vilket renderar en femteplats å världsrankningen.<br/><br/>För egen del så är jag i stort nöjd med mina resultat. Magic gick uselt då min Magic håller på att haverera och 2x gick några sekunder för långsamt. Jag satte personligt snittrekord på pyraminx med 16.92 (för övrigt samma snittid som på tvåan....), mest tack vare en ny Pyraminx som inte poppar. Square-1 var mest händleserik. Jag började med sub-2-min, vilket är bra för mig och gjorde att jag klarade tidsgränsen för fem försök. Tredje var en riktig turblandning där allt föll på plats och tiden slutade på 45 s, men blev DNF eftersom jag hade mittlagret fel. Så går det när man inte kollar tillräckligt. På ett sätt är jag glad över DNF:en, för annars skulle jag ha ett rekord som jag aldrig skulle slå i framtiden. Sista försöket blev också DNF då jag tappade fokus, gjorde fel i paritetsdragserien och kom bort helt och hållet. 3x flöt på bra, stabila lösningar och ett snitt på 41.33. Stabila tider även på 3x enhands runt 1:3x.xx, vilket dock inte räckte for fem försök. 4x gjorde jag en bra tid på 3:20.28, där jag antagligen skulle satt singelrekord om jag inte poppat en mittbit. <br/><br/>Mycket kul tävling och många nya kubvänner. Nu väntar <a href="http://www.worldcubeassociation.org/results/c.php?i=BangkokOpen2010" target="_blank">Bangkok Open 2010</a> och <a href="http://www.worldcubeassociation.org/results/c.php?i=JakartaOpen2010" target="_blank">Jakarta Open 2010</a> i januari nästa år!<br/><br/>
</div><ul class="controls"><li><a href="?NewComment&amp;post=21#comments"class="control">Kommentarer(4)</a></li></ul></div><!-- End of post --></div><div class="paging"></div><div class="footer"><a href="?About">Info</a><a href="?Categories">Kategorier</a><a href="?Login">Logga in</a><a href="?Home&amp;desktop">Desktop version</a></div></div><!-- End of container --></body></html>